/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms.ui;

import java.io.File;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import pms.model.Encounter;
import pms.model.ManagementSystem;
import pms.model.Patient;
import pms.model.Person;
import pms.utils.Utils;

/**
 *
 * @author akshatajadhav
 */
public class MainJFrame extends javax.swing.JFrame {
    
    ManagementSystem system;
    /**
     * Creates new form Main
     */
    public MainJFrame() {
        initComponents();
        system = new ManagementSystem();
        loadData();
        MainJPanel mjp = new MainJPanel(mainLayeredPane, system);
        displayPanel(mjp);
        setResizable(false);
    }

    public void displayPanel(JPanel panel) {
        mainLayeredPane.removeAll();
        mainLayeredPane.add(panel);
        mainLayeredPane.repaint();
        mainLayeredPane.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainLayeredPane = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PATIENT MANAGEMENT PORTAL");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientui/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainLayeredPane.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 590));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        mainLayeredPane.add(jPanel3, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainLayeredPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLayeredPane mainLayeredPane;
    // End of variables declaration//GEN-END:variables
    
    void loadData(){
       
        Person p = null;
        Patient patient = null;
        Encounter e = null;
        try {
            
            p = new Person("Peggy Carter","09/05/1955","Female","A-","pgc@gmail.com",9345654332L,165,60,143,"Orange County","Los Angeles",07652);
            system.addPerson(p);
            
            p = new Person("Steve Rogers","05/24/1955","Male","O+","capA@gmail.com",6785431288L,190,90,56,"Orange County","Los Angeles",07652);
            system.addPerson(p);
            
            p = new Person("Tony Stark","04/05/1970","Male","O-","ironM@gmail.com",7896578777L,183,80,101,"Lexington","Boston",02115);
            system.addPerson(p);
            
            p = new Person("Natasha Romanoff","10/10/1985","Female","AB+","blackwidow@gmail.com",6789876092L,180,55,9,"Manhattan","New York",05634);
            system.addPerson(p);
            patient = Utils.personToPatient(p);
            e=new Encounter(new Date(), 100, 100, 100, 100, 100);
            patient.getEncounterHistory().getEncounters().add(e);
            system.addPatient(patient);
            
            p = new Person("Bruce Banner","05/01/1970","Male","B+","hulk@gmail.com",9763421678L,180,75,46,"Manhattan","New York",05634);
            system.addPerson(p);
            patient = Utils.personToPatient(p);
            e=new Encounter(new Date(), 100, 100, 100, 100, 100);
            patient.getEncounterHistory().getEncounters().add(e);
            system.addPatient(patient);
            
            p = new Person("Peter Parker","06/12/2000","Male","O+","spidey@gmail.com",5216782450L,175,68,76,"NYC","New York",01235);
            system.addPerson(p);
            patient = Utils.personToPatient(p);
            e=new Encounter(Utils.dateTime(2019, 8, 8, 10, 30), 99, 110, 98, 100, 80);
            patient.getEncounterHistory().getEncounters().add(e);
            e=new Encounter(new Date(), 99, 110, 98, 100, 80); //latest entry, date
            patient.getEncounterHistory().getEncounters().add(e);
            system.addPatient(patient);
            
            p = new Person("Pepper Potts","03/28/1975","Female","B-","pepper@gmail.com",6735678222L,183,60,101,"Lexington","Boston",02215);
            system.addPerson(p);
            patient = Utils.personToPatient(p);
            e=new Encounter(Utils.dateTime(2019, 8, 8, 10, 30), 99, 110, 98, 100, 80);
            patient.getEncounterHistory().getEncounters().add(e);
            e=new Encounter(new Date(), 99, 110, 98, 100, 80); //latest entry, date
            patient.getEncounterHistory().getEncounters().add(e);
            system.addPatient(patient);
            
            p = new Person("Carol Danvers","03/28/1965","Female","O+","cptM@gmail.com",8786543245L,175,70,1,"NYC","New York",05432);
            system.addPerson(p);
            patient = Utils.personToPatient(p);
            e=new Encounter(Utils.dateTime(2019, 8, 8, 10, 30), 99, 110, 98, 100, 80);
            patient.getEncounterHistory().getEncounters().add(e);
            e=new Encounter(new Date(), 99, 110, 98, 100, 80); //latest entry, date
            patient.getEncounterHistory().getEncounters().add(e);
            system.addPatient(patient);
            
            Utils.copyToClipboard(system.getPatientDirectory().getPatientIDs().get(0));
        } catch (ParseException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
